### ISSUE TITLE
on OSX notification appeared but just black box

### ISSUE THREAD

**Issue by leemin0830** [robrighter/nw-desktop-notifications#3]
![2014-01-22 5 14 06](https://f.cloud.github.com/assets/5653885/1971925/32ed83de-833d-11e3-9fa6-7dab3790c72b.png)

hello! 
at first,  I think this is create feature for node-webkit. thank you for your sharing!
problem is just like title, on OSX notification appeared but just black box.

**Comment by jamesmortensen** [comment]
Just to bump this, I noticed this doesn't happen if the frame is set to true.  So it seems like it's a rendering problem of some kind.

**Comment by jamesmortensen** [comment]
This happens on nw 0.8.4 but not nw 0.9.0-rc2.  On 0.9.0-rc2 it seems to be working as expected.  Hope this helps.

**Comment by adam-lynch** [comment]
:+1:

**Comment by leemin0830** [comment]
what a great job! thank you :+1:
